Dockerfile, start.sh
* Run data reconciliation app on an alpine container with openjdk 8
installed.
=> BI-7492 Implement Dockerfile and startup script

Makefile
* Contains tasks to clean, test and build data reconciliation app using
the Maven build tool and Docker.
=> BI-7492 Implement Makefile

Tiltfile.dev, pom.xml
* Add jib to build docker container via Maven.
* Perform custom build if classes have been changed.
=> BI-7492 Implement Tiltfile

src/main/java/uk/gov/companieshouse/reconciliation/function/compare_collection/CompareCollectionRoute.java, src/main/resources/application.properties, src/main/resources/sql/company_collection.sql, src/main/resources/sql/company_count.sql, src/main/resources/sql/dsq_officers_collection.sql, src/test/java/uk/gov/companieshouse/reconciliation/function/compare_collection/CompareListRouteTest.java
* Rework endpoints to enforce separation between design-time and configuration time.
* Fix possible NullPointerException in CompareCollectionRoute if Oracle value null.
=> Rework application properties

src/main/java/uk/gov/companieshouse/reconciliation/component/elasticsearch/slicedscroll/ElasticsearchSlicedScrollEndpoint.java, src/main/java/uk/gov/companieshouse/reconciliation/component/elasticsearch/slicedscroll/ElasticsearchSlicedScrollProducer.java, src/main/java/uk/gov/companieshouse/reconciliation/component/elasticsearch/slicedscroll/client/ElasticsearchScrollingSearchClient.java, src/main/java/uk/gov/companieshouse/reconciliation/component/elasticsearch/slicedscroll/client/ElasticsearchScrollingSearchClientFactory.java, src/main/java/uk/gov/companieshouse/reconciliation/function/compare_collection/entity/ResourceList.java, src/main/java/uk/gov/companieshouse/reconciliation/function/compare_collection/transformer/CompareCollectionTransformer.java, src/main/java/uk/gov/companieshouse/reconciliation/service/elasticsearch/ElasticsearchCollectionRoute.java, src/main/java/uk/gov/companieshouse/reconciliation/service/mongo/MongoCollectionRoute.java, src/main/java/uk/gov/companieshouse/reconciliation/service/oracle/OracleCollectionRoute.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/reconciliation/component/elasticsearch/slicedscroll/client/ElasticsearchScrollingSearchClientTest.java, src/test/java/uk/gov/companieshouse/reconciliation/function/compare_collection/CompareCollectionRouteTest.java, src/test/java/uk/gov/companieshouse/reconciliation/service/elasticsearch/ElasticsearchCollectionRouteTest.java, src/test/java/uk/gov/companieshouse/reconciliation/service/mongo/MongoCollectionRouteTest.java, src/test/java/uk/gov/companieshouse/reconciliation/service/oracle/OracleCollectionRouteTest.java, src/test/resources/application-stubbed.properties
* Parameterise slice field; _uid not supported by ES7.
* Use Sets to aggregate results.
=> BI-7521 Parameterise slice field; performance improvements

src/main/java/uk/gov/companieshouse/reconciliation/disqualification/DisqualifiedOfficerCompareTrigger.java, src/main/java/uk/gov/companieshouse/reconciliation/service/oracle/OracleResultSplitter.java, src/test/java/uk/gov/companieshouse/reconciliation/disqualification/DisqualifiedOfficerCompareTriggerTest.java
* Interface of compare collection route has changed; headers in
disqualified officers pipeline has been changed accordingly.
=> BI-7521 Rework disqualified officers pipeline

src/main/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareMongoDBAlphaSearch.java, src/main/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareMongoDBPrimarySearch.java, src/main/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareOracleMongoDBTrigger.java, src/test/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareOracleMongoDBTriggerTest.java
* Set comparison description to company numbers in all three company
number comparison trigger routes.
=> Fix comparison description

src/main/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareMongoDBAlphaSearch.java, src/main/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareMongoDBPrimarySearch.java, src/main/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareOracleMongoDBTrigger.java, src/main/java/uk/gov/companieshouse/reconciliation/disqualification/DisqualifiedOfficerCompareTrigger.java, src/main/java/uk/gov/companieshouse/reconciliation/function/compare_collection/transformer/CompareCollectionTransformer.java, src/test/java/uk/gov/companieshouse/reconciliation/company/CompanyNumberCompareOracleMongoDBTriggerTest.java, src/test/java/uk/gov/companieshouse/reconciliation/company/CompareNumberCompareMongoDBAlphaSearchTest.java, src/test/java/uk/gov/companieshouse/reconciliation/company/CompareNumberCompareMongoDBPrimarySearchTest.java, src/test/java/uk/gov/companieshouse/reconciliation/disqualification/DisqualifiedOfficerCompareTriggerTest.java
* Replace hardcoded column heading with value retrieved from RecordType
header.
=> BI-7649 Parameterise column heading

src/main/java/uk/gov/companieshouse/reconciliation/service/elasticsearch/ElasticsearchTransformer.java, src/main/resources/elasticsearch/primary_company.json, src/test/java/uk/gov/companieshouse/reconciliation/service/elasticsearch/ElasticsearchCollectionRouteTest.java, src/test/java/uk/gov/companieshouse/reconciliation/service/elasticsearch/ElasticsearchTransformerTest.java
* Trim name segments from Elasticsearch and concatenate if present.
=> BI-7522 Fix whitespace issue

README.md, Tiltfile.dev
* Add project README file
* Update image ref in Tiltfile
=> BI-8072 Add README.md to data reconciliation app

src/main/java/uk/gov/companieshouse/reconciliation/service/KafkaRoute.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/reconciliation/service/KafkaRouteTest.java, src/test/resources/application-stubbed.properties
* Implement new route to terminate application after all emails have
been sent via Kafka.
Related:
[BI-7977](https://companieshouse.atlassian.net/browse/BI-7977)
=> Shutdown application after comparisons complete

src/main/java/uk/gov/companieshouse/reconciliation/service/ShutdownRoute.java
* Implement a new route to automatically shutdown the application by closing the Spring application context after all comparisons have been performed.
=> Implement shutdown route

src/main/java/uk/gov/companieshouse/reconciliation/service/ShutdownRoute.java
* Fixes an issue whereby the application continues to run even after the
Spring application context has been stopped.
=> Forcibly exit after spring context has stopped

README.md
Refine README to split environment variables by comparison group
[BI-8364](https://companieshouse.atlassian.net/browse/BI-8364)
=> BI-8364 - Refine README to split environment variables by comparison group

src/main/resources/sql/insolvency_cases.sql
* Fixes duplicate key issue noted on staging environment.
=> BI-8471 Exclude duplicates from insolvency cases query

src/main/resources/logback-spring.xml
* Add basic Logback configuration file
=> Switch on debug logging

src/main/resources/sql/company_status/company_status_sql_queries.xml
Replaces OR statements within company status queries with UNIONs.
Remove column aliases from company status queries 
[BI-8524](https://companieshouse.atlassian.net/browse/BI-8524)
=> BI-8524 replace OR queries with UNION equivalent

src/main/resources/sql/company_collection.sql, src/main/resources/sql/company_count.sql
Amended SQL queries for company count and company collection
Resolves BI-12144
=> Amended SQL queries for company count and company collection

terraform/groups/ecs-service/variables.tf
PR to increase service cpu and memory
=> increasing the cpu and memory

terraform/groups/ecs-service/variables.tf
=> increasing the cpu and mem

terraform/groups/ecs-service/variables.tf
=> increasing the memory

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
modifying scaling schedule times and adding desired task and min task
=> modifying scaling schedule times and adding desired task and min task

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> increasing  task count in cidev

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
increasing cron time and reverting the max task
=> increasing cron time and reverting the max task

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> modifying var

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
scale down and up cron set to 15mins interval
=> scaledown and up cron set to 15mins interval

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> removing not needed var

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
setting desired task count to zero  as I am testing the scaleup and scale down effects on app
=> setting desired task count to zero 

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
testing my terraform module branch to fix health check status issue
=> ju-954 fix healthcheck issue

terraform/groups/ecs-service/main.tf
small change to modify the command
=> modified the command

terraform/groups/ecs-service/main.tf
=> cleaning up repo

terraform/groups/ecs-service/locals.tf
empty pr to trigger rebuild of service.
=> JU-954-empty pr to trigger rebuild

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf
=> JU-954- empty pr to trigger pipeline

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> modifying cron time

terraform/groups/ecs-service/main.tf
=> added ecs cluster arn

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/variables.tf
=> modifying cron time and var

terraform/groups/ecs-service/data.tf
adding datasource to fix iam issue
=> adding datasource to fix iam issue

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/variables.tf
=> env var modifications

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
JU-954
bumping up tag 
adding env var required for health check 
modified the cron time
=> bumping up tag and adding env var required

terraform/groups/ecs-service/main.tf
testing adding scheduler group needed to add each scheduler to specific group
=> adding scheduler group

terraform/groups/ecs-service/main.tf
=> bump tag to the latest tf tag

terraform/groups/ecs-service/main.tf
Reverts companieshouse/data-reconciliation#133
=> Revert "testing eventrule feature for event based approach for containers "

terraform/groups/ecs-service/variables.tf
=> modify env var

terraform/groups/ecs-service/lambda.tf, terraform/groups/ecs-service/variables.tf
=> modify lambda name

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> modify shutdown cron time

pom.xml
test fix for class not found v2
=> test fix for class not found v2

pom.xml
Reverts companieshouse/data-reconciliation#145
=> Revert "test fix for class not found v2"

ecs-image-build/docker_start.sh
=> triggering app rebuild

pom.xml
These changes resulted in extreme heap usage and ultimately OOM issues in staging, the source of which is unclear
=> Revert tech debt dependency changes
